// Author: Navjyot Nishant
// Created: 2026-08-15
// Last updated: 2026-08-15
// Description: Documentation navigation, ordered as someone reads it.

import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Explicit rather than autogenerated.
//
// Autogeneration orders by filename, which puts the reference material
// someone needs on day thirty above the install they need in the first
// minute — and the fix is then to rename files after their position, which
// is how you end up with 03-install.md.
//
// The order here is the reading order: install, prove it works, understand
// what it recorded, then the two things a reader gets wrong if nobody tells
// them — what each agent can actually report, and what the numbers do not
// claim.
const sidebars: SidebarsConfig = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Getting started',
      collapsed: false,
      items: [
        'getting-started/install',
        'getting-started/first-commit',
        'getting-started/the-trailer',
      ],
    },
    {
      type: 'category',
      label: 'Dashboards',
      collapsed: false,
      items: [
        'dashboards/datalake-setup',
        'dashboards/the-dashboards',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      items: [
        'reference/agent-capabilities',
        'reference/what-the-numbers-mean',
        'reference/how-attribution-works',
        'reference/privacy',
        'reference/commands',
      ],
    },
  ],
};

export default sidebars;
